In [92]:
import numpy as np
import pandas as pd

In [93]:
cols_power = [18, 5, 8, 11, 17, 6,  1, 20]
df = pd.read_excel('0DOE.xlsx',sheet_name='DOE').iloc[1:,1:9]

In [94]:
df

    红眼  橄榄  冰车  气球  白眼  舞王  撑杆  密度
1   -1  -1  -1  -1  -1  -1  -1  -1
2   -1  -1  -1  -1   1   1  -1   1
3   -1  -1  -1   1  -1   1   1  -1
4   -1  -1  -1   1   1  -1   1   1
5   -1  -1   1  -1  -1   1  -1   1
6   -1  -1   1  -1   1  -1  -1  -1
7   -1  -1   1   1  -1  -1   1   1
8   -1  -1   1   1   1   1   1  -1
9   -1   1  -1  -1  -1   1   1  -1
10  -1   1  -1  -1   1  -1   1   1
11  -1   1  -1   1  -1  -1  -1  -1
12  -1   1  -1   1   1   1  -1   1
13  -1   1   1  -1  -1  -1   1   1
14  -1   1   1  -1   1   1   1  -1
15  -1   1   1   1  -1   1  -1   1
16  -1   1   1   1   1  -1  -1  -1
17   1  -1  -1  -1  -1   1   1   1
18   1  -1  -1  -1   1  -1   1  -1
19   1  -1  -1   1  -1  -1  -1   1
20   1  -1  -1   1   1   1  -1  -1
21   1  -1   1  -1  -1  -1   1  -1
22   1  -1   1  -1   1   1   1   1
23   1  -1   1   1  -1   1  -1  -1
24   1  -1   1   1   1  -1  -1   1
25   1   1  -1  -1  -1  -1  -1   1
26   1   1  -1  -1   1   1  -1  -1
27   1   1  -1   1  -1   1   1   1
28   1   1  -1   1   1  -1   1  -1
29   1   1   1  -1  -1   1  -1  -1
30   1   1   1  -1   1  -1  -1   1
31   1   1   1   1  -1  -1   1  -1
32   1   1   1   1   1   1   1   1

In [95]:
df.replace(-1, 0, inplace=True)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_35896\54590359.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(-1, 0, inplace=True)

In [96]:
df['ans'] = df.apply(
    lambda row: sum([
        row[i] * (1 << (cols_power[idx])) 
        for idx, i in enumerate(df.columns)
    ]),
    axis=1
)
df['ans'] = df['ans'].apply(lambda x: f'0b{x:021b}')

In [97]:
df

    红眼  橄榄  冰车  气球  白眼  舞王  撑杆  密度                      ans
1    0   0   0   0   0   0   0   0  0b000000000000000000000
2    0   0   0   0   1   1   0   1  0b100100000000001000000
3    0   0   0   1   0   1   1   0  0b000000000100001000010
4    0   0   0   1   1   0   1   1  0b100100000100000000010
5    0   0   1   0   0   1   0   1  0b100000000000101000000
6    0   0   1   0   1   0   0   0  0b000100000000100000000
7    0   0   1   1   0   0   1   1  0b100000000100100000010
8    0   0   1   1   1   1   1   0  0b000100000100101000010
9    0   1   0   0   0   1   1   0  0b000000000000001100010
10   0   1   0   0   1   0   1   1  0b100100000000000100010
11   0   1   0   1   0   0   0   0  0b000000000100000100000
12   0   1   0   1   1   1   0   1  0b100100000100001100000
13   0   1   1   0   0   0   1   1  0b100000000000100100010
14   0   1   1   0   1   1   1   0  0b000100000000101100010
15   0   1   1   1   0   1   0   1  0b100000000100101100000
16   0   1   1   1   1   0   0   0  0b000100000100100100000
17   1   0   0   0   0   1   1   1  0b101000000000001000010
18   1   0   0   0   1   0   1   0  0b001100000000000000010
19   1   0   0   1   0   0   0   1  0b101000000100000000000
20   1   0   0   1   1   1   0   0  0b001100000100001000000
21   1   0   1   0   0   0   1   0  0b001000000000100000010
22   1   0   1   0   1   1   1   1  0b101100000000101000010
23   1   0   1   1   0   1   0   0  0b001000000100101000000
24   1   0   1   1   1   0   0   1  0b101100000100100000000
25   1   1   0   0   0   0   0   1  0b101000000000000100000
26   1   1   0   0   1   1   0   0  0b001100000000001100000
27   1   1   0   1   0   1   1   1  0b101000000100001100010
28   1   1   0   1   1   0   1   0  0b001100000100000100010
29   1   1   1   0   0   1   0   0  0b001000000000101100000
30   1   1   1   0   1   0   0   1  0b101100000000100100000
31   1   1   1   1   0   0   1   0  0b001000000100100100010
32   1   1   1   1   1   1   1   1  0b101100000100101100010

In [98]:
for v in df['ans'].values:
    print(v, end=',\n')

0b000000000000000000000,
0b100100000000001000000,
0b000000000100001000010,
0b100100000100000000010,
0b100000000000101000000,
0b000100000000100000000,
0b100000000100100000010,
0b000100000100101000010,
0b000000000000001100010,
0b100100000000000100010,
0b000000000100000100000,
0b100100000100001100000,
0b100000000000100100010,
0b000100000000101100010,
0b100000000100101100000,
0b000100000100100100000,
0b101000000000001000010,
0b001100000000000000010,
0b101000000100000000000,
0b001100000100001000000,
0b001000000000100000010,
0b101100000000101000010,
0b001000000100101000000,
0b101100000100100000000,
0b101000000000000100000,
0b001100000000001100000,
0b101000000100001100010,
0b001100000100000100010,
0b001000000000101100000,
0b101100000000100100000,
0b001000000100100100010,
0b101100000100101100010,