In [1]:
import pandas as pd
import statsmodels.api as sm
from matplotlib import pyplot as plt  

df = pd.read_excel('2.0阳光信息.xlsx',usecols=['Y','红','车','橄','气','舞','杆','白','权重和'])
df['权重和']=df['权重和']/10000

df1 = df[(df['车'] == 1) & (df['橄'] == 1)]
df2 = df[~((df['车'] == 1) & (df['橄'] == 1))]

In [2]:
def OLSmodel(df,const=True):
    X = df.iloc[:,1:]
    y = -df['Y']
    X_sm = sm.add_constant(X) if const else X
    model_sm = sm.OLS(y, X_sm).fit()
    print(model_sm.summary())
    return pd.DataFrame(model_sm.params)

In [3]:
OLSmodel(df[['Y','车','橄','气','舞','杆','权重和']],False)

                                 OLS Regression Results
=======================================================================================
Dep. Variable:                      Y   R-squared (uncentered):                   0.846
Model:                            OLS   Adj. R-squared (uncentered):              0.797
Method:                 Least Squares   F-statistic:                              17.35
Date:                Sat, 03 May 2025   Prob (F-statistic):                    8.72e-07
Time:                        09:25:32   Log-Likelihood:                         -179.18
No. Observations:                  25   AIC:                                      370.4
Df Residuals:                      19   BIC:                                      377.7
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
车            617.8601    195.076      3.167      0.005     209.562    1026.158
橄            730.4251    168.539      4.334      0.000     377.670    1083.181
气            911.1419    163.308      5.579      0.000     569.335    1252.949
舞            586.3509    176.980      3.313      0.004     215.927     956.774
杆            299.6206    200.483      1.494      0.151    -119.996     719.237
权重和        -1017.4024    195.568     -5.202      0.000   -1426.732    -608.073
==============================================================================
Omnibus:                        0.898   Durbin-Watson:                   1.418
Prob(Omnibus):                  0.638   Jarque-Bera (JB):                0.759
Skew:                          -0.063   Prob(JB):                        0.684
Kurtosis:                       2.156   Cond. No.                         7.91
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.

               0
车     617.860093
橄     730.425070
气     911.141931
舞     586.350852
杆     299.620575
权重和 -1017.402429

In [4]:
OLSmodel(df1[['Y','气','白','权重和']],True)

                            OLS Regression Results
==============================================================================
Dep. Variable:                      Y   R-squared:                       0.895
Model:                            OLS   Adj. R-squared:                  0.833
Method:                 Least Squares   F-statistic:                     14.26
Date:                Sat, 03 May 2025   Prob (F-statistic):            0.00694
Time:                        09:25:32   Log-Likelihood:                -62.679
No. Observations:                   9   AIC:                             133.4
Df Residuals:                       5   BIC:                             134.1
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2036.6840   1272.870      1.600      0.170   -1235.332    5308.700
气           1439.7709    256.862      5.605      0.002     779.485    2100.057
白           -645.2170    246.015     -2.623      0.047   -1277.620     -12.814
权重和        -1365.3537    860.200     -1.587      0.173   -3576.567     845.860
==============================================================================
Omnibus:                        0.006   Durbin-Watson:                   2.312
Prob(Omnibus):                  0.997   Jarque-Bera (JB):                0.171
Skew:                           0.002   Prob(JB):                        0.918
Kurtosis:                       2.324   Cond. No.                         25.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

c:\MyFile\anaconda3\Lib\site-packages\scipy\stats\_axis_nan_policy.py:531: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  res = hypotest_fun_out(*samples, **kwds)

                 0
const  2036.683963
气      1439.770900
白      -645.217042
权重和   -1365.353698

In [5]:
OLSmodel(df2[['Y','车','橄','气','舞','杆','白','权重和']],False)

                                 OLS Regression Results
=======================================================================================
Dep. Variable:                      Y   R-squared (uncentered):                   0.832
Model:                            OLS   Adj. R-squared (uncentered):              0.702
Method:                 Least Squares   F-statistic:                              6.385
Date:                Sat, 03 May 2025   Prob (F-statistic):                     0.00648
Time:                        09:25:32   Log-Likelihood:                         -112.22
No. Observations:                  16   AIC:                                      238.4
Df Residuals:                       9   BIC:                                      243.8
Df Model:                           7
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
车           1092.8191    419.058      2.608      0.028     144.845    2040.794
橄            929.8762    264.201      3.520      0.007     332.211    1527.541
气           1001.7801    219.885      4.556      0.001     504.366    1499.194
舞            762.1884    239.552      3.182      0.011     220.284    1304.093
杆            798.0179    373.708      2.135      0.061     -47.369    1643.405
白            356.8283    204.631      1.744      0.115    -106.078     819.735
权重和        -1683.7999    446.789     -3.769      0.004   -2694.508    -673.092
==============================================================================
Omnibus:                        1.171   Durbin-Watson:                   2.170
Prob(Omnibus):                  0.557   Jarque-Bera (JB):                0.477
Skew:                          -0.423   Prob(JB):                        0.788
Kurtosis:                       2.980   Cond. No.                         15.0
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.

c:\MyFile\anaconda3\Lib\site-packages\scipy\stats\_axis_nan_policy.py:531: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  res = hypotest_fun_out(*samples, **kwds)

               0
车    1092.819118
橄     929.876226
气    1001.780068
舞     762.188412
杆     798.017935
白     356.828262
权重和 -1683.799909