In [2]:
# prob
import numpy as np
import pandas as pd
from math import comb

offset = [-2,-3,0,-4]
name = ['DE','NE','PE','RE']

ans_dic = {}
for sc in range(4):
    total = 19+2-1+offset[sc]
    ans = []
    for i in range(10):
        # ans.append(f'{comb(total-i,9-i)*1.0/comb(total,9):.10f}')
        ans.append(comb(total-i,9-i)*1.0/comb(total,9))
    ans_dic[name[sc]] = ans

df = pd.DataFrame(ans_dic)
df

         DE        NE        PE        RE
0  1.000000  1.000000  1.000000  1.000000
1  0.500000  0.529412  0.450000  0.562500
2  0.235294  0.264706  0.189474  0.300000
3  0.102941  0.123529  0.073684  0.150000
4  0.041176  0.052941  0.026006  0.069231
5  0.014706  0.020362  0.008127  0.028846
6  0.004525  0.006787  0.002167  0.010490
7  0.001131  0.001851  0.000464  0.003147
8  0.000206  0.000370  0.000071  0.000699
9  0.000021  0.000041  0.000006  0.000087

In [3]:
# mean interval
1/df

             DE            NE             PE            RE
0      1.000000      1.000000       1.000000      1.000000
1      2.000000      1.888889       2.222222      1.777778
2      4.250000      3.777778       5.277778      3.333333
3      9.714286      8.095238      13.571429      6.666667
4     24.285714     18.888889      38.452381     14.444444
5     68.000000     49.111111     123.047619     34.666667
6    221.000000    147.333333     461.428571     95.333333
7    884.000000    540.222222    2153.333333    317.777778
8   4862.000000   2701.111111   13996.666667   1430.000000
9  48620.000000  24310.000000  167960.000000  11440.000000

In [4]:
# longest
import matplotlib.pyplot as plt
from math import log2,exp
import random
'''
def prob_rube(p,M,n):
    return 1-(1-p**n)**M
def prob_newrube(p,M,n):
    return 1-(1-p**n*(1-p))**M
def prob_list(p,M,n):
    f = np.ones(M+1)
    f[n]=1-p**n
    coef = p**n*(1-p)
    for k in range(n+1,M+1):
        f[k] = f[k-1]- coef*f[k-n-1]
    return 1-f[M]
def prob_eign(p,M,n):
    lamb = 1-p**n*(1-p)
    c = (1-p**n)/(lamb**n)
    return 1-c*lamb**M
'''
def prob_poisson(p,M,n):
    return 1-exp(-M*p**n*(1-p))

M = 2**32

i_dict = {} 
for sc in range(4):
    i_dict[name[sc]] = []
    for m in range(0,10):
        p = df[name[sc]][m]
        ans_list = []
        idx_list = []
        for n in range(1,50):
            ans = prob_poisson(p,M,n)
            if ans>0.975:  continue
            ans_list.append(ans)
            idx_list.append(n)
            if ans<0.025:    break
        sub_df = pd.DataFrame({'len':idx_list,'prob':ans_list})
        
        # print(f'{name[sc]}指定{m}种:\n{sub_df.to_string(index=False)}\n')
        
        i_dict[name[sc]].append([idx_list[0]-1,idx_list[-1]])
i_df = pd.DataFrame(i_dict)

i_df

         DE        NE        PE        RE
0    [0, 1]    [0, 1]    [0, 1]    [0, 1]
1  [29, 37]  [31, 40]  [25, 32]  [34, 44]
2  [14, 18]  [15, 20]  [12, 16]  [17, 22]
3   [9, 12]   [9, 13]   [7, 10]  [10, 14]
4    [6, 9]    [7, 9]    [5, 8]   [7, 10]
5    [4, 7]    [5, 7]    [4, 6]    [5, 8]
6    [3, 5]    [4, 6]    [3, 5]    [4, 6]
7    [3, 4]    [3, 5]    [2, 4]    [3, 5]
8    [2, 4]    [2, 4]    [2, 3]    [2, 4]
9    [1, 3]    [2, 3]    [1, 3]    [2, 3]

In [8]:
# 红橄
prob_int = df['NE'][2]
# 只红/只橄
prob_minus = df['NE'][1]-df['NE'][2]
# 无红无橄
prob_1z = 1-prob_int-2*prob_minus
prob_int,prob_int,prob_1z

(0.2647058823529412, 0.2647058823529412, 0.20588235294117652)

In [9]:
530*prob_int - 200*prob_minus -  50*prob_minus - 800*prob_1z

-90.5882352941177