In [81]:
import pandas as pd
import statsmodels.api as sm
from matplotlib import pyplot as plt  

df = pd.read_excel('2.0阳光信息.xlsx')
df['权重和']=df['权重和']/10000
df = df.drop('flag',axis=1)
# df
df.columns

Index(['Y', '路障', '撑杆', '铁桶', '读报', '铁门', '橄榄', '舞王', '潜水', '冰车', '海豚', '小丑',
       '气球', '矿工', '跳跳', '蹦极', '扶梯', '投篮', '白眼', '红眼', '权重和'],
      dtype='object')

In [82]:
def OLSmodel(df,const=True):
    X = df.iloc[:,1:]
    y = -df['Y']
    X_sm = sm.add_constant(X) if const else X
    model_sm = sm.OLS(y, X_sm).fit()
    print(model_sm.summary())
    return pd.DataFrame(model_sm.params)

In [83]:
# handle
df['Y'] -= 51.34

In [84]:
df

,Y,路障,撑杆,铁桶,读报,铁门,橄榄,舞王,潜水,冰车,...,小丑,气球,矿工,跳跳,蹦极,扶梯,投篮,白眼,红眼,权重和
0,623.66,1,1,0,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,1,1.0901
1,-951.34,1,0,0,0,0,1,0,0,1,...,0,1,0,1,1,0,0,1,1,1.0901
2,1048.66,1,1,1,0,0,0,1,0,0,...,1,0,1,0,1,1,0,1,0,1.1901
3,-26.34,1,0,1,0,1,1,0,0,0,...,1,1,0,1,0,1,1,0,0,1.6401
4,-76.34,1,1,1,0,0,1,0,0,0,...,1,0,1,1,0,0,1,0,1,1.3901
5,773.66,1,1,0,1,1,1,1,0,0,...,1,0,0,0,1,1,0,0,0,1.2901
6,273.66,1,1,0,1,1,0,1,0,0,...,1,1,0,0,0,0,1,1,0,1.4901
7,-951.34,1,0,1,1,0,0,0,0,1,...,0,1,1,1,1,0,0,1,1,1.3901
8,148.66,1,1,0,1,0,1,0,0,0,...,0,0,1,0,0,1,1,0,1,1.0901
9,348.66,1,0,1,1,1,0,0,0,0,...,0,1,0,1,0,0,0,1,1,1.4401
10,-876.34,0,0,0,1,1,0,0,0,1,...,0,1,1,0,1,1,1,0,1,1.3401
11,298.66,1,1,0,0,1,1,0,0,0,...,1,1,0,1,0,0,1,1,0,1.5901
12,1073.66,1,0,1,1,0,0,1,0,1,...,1,0,0,1,0,1,0,0,0,1.1401
13,-901.34,1,0,1,0,0,0,0,0,1,...,1,1,1,1,1,0,0,0,1,1.2401
14,273.66,0,0,1,1,0,1,1,0,0,...,0,1,0,1,0,1,0,1,0,1.2901
15,323.66,1,0,1,1,0,0,0,0,1,...,1,0,1,1,1,1,1,0,0,1.2901
16,448.66,1,0,1,1,0,1,0,0,1,...,1,0,0,1,0,1,1,0,0,1.3901
17,-301.34,0,0,0,1,0,0,1,0,1,...,1,1,0,1,1,0,1,0,1,1.0901
18,23.66,1,1,1,0,0,1,1,0,0,...,1,1,0,0,0,1,0,1,0,1.4901
19,-651.34,1,0,0,1,1,1,0,0,1,...,0,0,0,1,0,1,0,0,1,1.2901
20,1373.66,1,1,1,0,0,0,1,0,0,...,1,0,1,1,0,1,0,1,0,1.2901
21,-226.34,1,0,1,0,1,0,1,0,1,...,0,1,1,1,0,0,0,0,0,1.4901
22,-51.34,1,1,1,0,1,0,1,0,1,...,0,1,0,0,0,1,0,0,1,1.6901
23,323.66,1,0,1,1,1,1,1,0,1,...,0,0,1,0,0,1,0,0,0,1.5901
24,373.66,1,0,0,1,1,0,1,0,0,...,1,0,1,0,0,1,1,0,1,1.2401
25,-851.34,1,0,0,0,0,0,0,0,0,...,0,1,1,1,1,0,1,1,1,0.9401
26,1548.66,1,0,1,1,1,1,1,0,0,...,0,0,0,1,1,0,1,1,0,1.5901
27,48.66,1,0,1,1,0,0,1,0,1,...,0,0,1,0,1,1,0,0,1,1.1401
28,-451.34,1,1,0,1,1,0,0,0,0,...,0,1,1,1,1,0,1,1,0,1.4901
29,-1376.34,1,1,0,1,0,1,0,0,1,...,1,1,0,0,1,1,0,0,1,1.3401
30,-401.34,1,0,0,1,0,0,1,0,0,...,1,1,1,1,0,0,0,1,1,1.0901
31,1123.66,1,1,1,1,1,0,0,0,0,...,1,0,0,1,0,1,1,0,1,1.6401
32,498.66,1,1,0,1,1,0,0,0,1,...,1,0,1,1,1,0,1,0,0,1.4401
33,373.66,1,1,1,0,0,1,1,0,0,...,1,0,1,0,1,1,0,1,0,1.3901
34,-201.34,1,1,1,1,1,1,0,0,0,...,0,1,0,1,0,0,1,0,1,1.8401
35,-451.34,1,0,1,1,0,1,0,0,1,...,0,1,0,0,1,1,1,0,0,1.3901
36,-201.34,1,0,0,1,1,1,0,0,1,...,1,0,0,1,1,0,0,0,1,1.2901
37,948.66,1,0,1,1,1,1,0,0,1,...,1,0,0,0,0,1,1,1,0,1.7901
38,-1101.34,0,0,1,1,1,1,0,0,1,...,0,1,1,0,0,0,1,0,1,1.7401
39,373.66,0,1,1,1,1,1,0,0,0,...,1,0,0,0,1,1,0,1,1,1.6401
40,723.66,1,0,0,1,0,1,1,0,0,...,1,0,0,1,1,1,0,1,0,0.9901
41,-376.34,1,1,0,1,1,0,0,0,1,...,1,1,1,0,0,0,1,0,0,1.5401
42,-1376.34,1,0,1,0,0,1,1,0,1,...,1,0,0,1,1,0,0,0,1,1.2401
43,-1226.34,1,1,1,0,0,1,0,0,1,...,0,1,1,1,0,1,0,0,0,1.5401
44,-1151.34,1,1,0,0,0,1,1,0,1,...,0,1,1,1,0,0,1,0,0,1.3901
45,-776.34,1,0,1,1,0,1,0,0,1,...,0,1,0,0,1,0,1,1,1,1.5401
46,948.66,1,1,0,1,1,0,0,0,0,...,1,0,1,0,0,0,1,1,1,1.3901
47,-376.34,1,1,0,0,1,0,0,0,1,...,0,1,1,0,1,1,0,0,0,1.2901
48,773.66,1,1,1,0,1,0,0,0,1,...,0,0,1,0,1,0,1,0,0,1.4401
49,1248.66,1,0,0,0,0,0,1,0,1,...,1,0,0,1,0,1,1,1,0,1.0401
50,1398.66,1,0,1,1,1,0,1,0,1,...,0,0,0,0,0,1,1,1,0,1.5901

In [85]:
# sample all
# OLSmodel(df[['Y', '撑杆', '铁桶',  '铁门', '橄榄', '舞王', '冰车', '气球', '矿工',  '蹦极', '扶梯', '投篮', '白眼', '红眼', '权重和']],True)

OLSmodel(df[['Y', '铁桶',  '铁门', '橄榄',  '冰车', '气球', '矿工',  '蹦极',  '白眼', '红眼']],True)

# OLSmodel(df[['Y',  '橄榄',  '冰车',  '气球', '矿工',  '蹦极',   '红眼']],True)

                            OLS Regression Results
==============================================================================
Dep. Variable:                      Y   R-squared:                       0.881
Model:                            OLS   Adj. R-squared:                  0.854
Method:                 Least Squares   F-statistic:                     33.58
Date:                Sun, 04 May 2025   Prob (F-statistic):           3.82e-16
Time:                        19:52:43   Log-Likelihood:                -357.48
No. Observations:                  51   AIC:                             735.0
Df Residuals:                      41   BIC:                             754.3
Df Model:                           9
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1300.9834    184.523     -7.051      0.000   -1673.636    -928.331
铁桶          -172.7762     88.732     -1.947      0.058    -351.975       6.422
铁门          -185.6082     90.724     -2.046      0.047    -368.829      -2.387
橄榄           608.0540     96.308      6.314      0.000     413.555     802.553
冰车           424.0030    100.617      4.214      0.000     220.804     627.202
气球           941.5738     86.472     10.889      0.000     766.940    1116.208
矿工           430.6432     96.948      4.442      0.000     234.853     626.433
蹦极           172.9115     89.090      1.941      0.059      -7.010     352.833
白眼          -190.2794    104.419     -1.822      0.076    -401.158      20.600
红眼           510.2896     87.854      5.808      0.000     332.866     687.713
==============================================================================
Omnibus:                       31.252   Durbin-Watson:                   1.771
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               77.922
Skew:                           1.708   Prob(JB):                     1.20e-17
Kurtosis:                       8.000   Cond. No.                         9.85
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

                 0
const -1300.983391
铁桶     -172.776238
铁门     -185.608178
橄榄      608.054003
冰车      424.002961
气球      941.573840
矿工      430.643181
蹦极      172.911478
白眼     -190.279387
红眼      510.289569