In [163]:
import pandas as pd
import statsmodels.api as sm
from matplotlib import pyplot as plt  

df = pd.read_excel('2.1阳光信息.xlsx')
df['权重和']=df['权重和']/10000
df = df.drop('flag',axis=1)
# df
df.columns

Index(['Y', '路障', '撑杆', '铁桶', '读报', '铁门', '橄榄', '舞王', '潜水', '冰车', '海豚', '小丑',
       '气球', '矿工', '跳跳', '蹦极', '扶梯', '投篮', '白眼', '红眼', '权重和'],
      dtype='object')

In [164]:
def OLSmodel(df,const=True):
    X = df.iloc[:,1:]
    y = -df['Y']
    X_sm = sm.add_constant(X) if const else X
    model_sm = sm.OLS(y, X_sm).fit()
    print(model_sm.summary())
    return pd.DataFrame(model_sm.params)

In [165]:
# sample 10
OLSmodel(df[df['红眼']==0][['Y',  '橄榄', '冰车', '气球', '权重和']],False)

                                 OLS Regression Results
=======================================================================================
Dep. Variable:                      Y   R-squared (uncentered):                   0.946
Model:                            OLS   Adj. R-squared (uncentered):              0.910
Method:                 Least Squares   F-statistic:                              26.19
Date:                Sun, 04 May 2025   Prob (F-statistic):                    0.000610
Time:                        07:15:11   Log-Likelihood:                         -64.660
No. Observations:                  10   AIC:                                      137.3
Df Residuals:                       6   BIC:                                      138.5
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
橄榄           382.9018    340.247      1.125      0.303    -449.654    1215.457
冰车           177.4671    230.446      0.770      0.470    -386.414     741.348
气球           989.1990    251.372      3.935      0.008     374.115    1604.283
权重和         -734.6030    190.716     -3.852      0.008   -1201.269    -267.937
==============================================================================
Omnibus:                        0.679   Durbin-Watson:                   2.445
Prob(Omnibus):                  0.712   Jarque-Bera (JB):                0.380
Skew:                           0.423   Prob(JB):                        0.827
Kurtosis:                       2.555   Cond. No.                         12.5
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.

c:\MyFile\anaconda3\Lib\site-packages\scipy\stats\_axis_nan_policy.py:531: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  res = hypotest_fun_out(*samples, **kwds)

              0
橄榄   382.901772
冰车   177.467098
气球   989.198988
权重和 -734.602994

In [166]:
# handle
df['Y'][:10] -= 65.52
df['Y'][10:] -= 37.17

C:\Users\Administrator\AppData\Local\Temp\ipykernel_27136\3292867118.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Y'][:10] -= 65.52
C:\Users\Administrator\AppData\Local\Temp\ipykernel_27136\3292867118.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Y'][:10] -= 65.52
C:\Users\Administrator\AppData\Local\Temp\ipykernel_27136\3292867118.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ 634.48 -540.52  934.48 1084.48  609.48  284.48 -315.52 -440.52 -540.52
  584.48]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df['Y'][:10] -= 65.52
C:\Users\Administrator\AppData\Local\Temp\ipykernel_27136\3292867118.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Y'][10:] -= 37.17

In [167]:
df

,Y,路障,撑杆,铁桶,读报,铁门,橄榄,舞王,潜水,冰车,...,小丑,气球,矿工,跳跳,蹦极,扶梯,投篮,白眼,红眼,权重和
0,634.48,1,1,0,1,0,0,1,0,1,...,0,0,1,0,1,0,1,1,0,1.1401
1,-540.52,1,0,1,0,0,1,1,0,0,...,1,1,1,0,1,0,0,1,0,1.2901
2,934.48,1,0,0,0,1,0,1,0,1,...,1,0,1,1,0,0,1,1,0,1.3901
3,1084.48,1,1,1,1,1,0,1,0,1,...,0,0,1,0,1,0,0,1,0,1.6401
4,609.48,1,1,0,1,1,1,0,0,0,...,0,0,1,1,1,1,0,1,0,1.4401
5,284.48,1,0,1,0,0,0,1,0,1,...,1,0,1,1,1,1,0,0,0,1.1401
6,-315.52,1,0,0,1,1,1,1,0,1,...,0,1,0,0,1,0,0,1,0,1.4401
7,-440.52,1,1,1,1,0,1,0,0,0,...,1,1,1,0,1,0,0,0,0,1.3401
8,-540.52,1,1,1,0,0,1,1,0,1,...,1,1,0,0,0,0,1,1,0,1.7401
9,584.48,0,0,1,1,0,0,1,0,1,...,0,0,1,1,1,1,1,0,0,1.1901
10,137.83,0,0,1,1,0,0,0,0,1,...,1,1,0,0,0,1,1,1,1,1.4401
11,-362.17,1,1,1,1,0,1,1,0,0,...,0,0,1,0,0,1,0,0,1,1.3401
12,-1012.17,1,0,1,0,0,1,0,0,1,...,1,1,0,0,1,1,0,1,1,1.4901
13,-787.17,1,1,0,1,0,0,0,0,1,...,1,1,1,0,0,0,1,0,1,1.2901
14,-62.17,1,1,1,1,0,0,1,0,0,...,0,1,0,0,0,1,0,1,1,1.3901
15,-512.17,1,1,0,1,1,0,1,0,0,...,0,1,1,1,0,1,0,0,1,1.4901
16,537.83,1,0,1,1,1,1,0,0,1,...,0,0,0,0,1,1,1,0,1,1.6401
17,-1937.17,1,0,0,1,0,1,1,0,1,...,0,1,0,0,1,0,1,0,1,1.1901
18,87.83,1,0,0,1,0,0,0,0,1,...,0,0,1,0,0,1,1,1,1,1.0401
19,62.83,1,1,1,0,1,1,0,0,0,...,0,1,0,0,0,1,0,1,1,1.7401
20,-37.17,1,1,0,0,1,0,0,0,0,...,0,1,0,0,1,0,1,1,1,1.2901
21,262.83,1,0,0,1,1,1,0,0,1,...,0,0,0,0,1,0,0,1,1,1.2401
22,962.83,1,0,0,1,1,0,0,0,1,...,1,0,0,1,0,0,1,0,1,1.2401
23,137.83,1,1,0,1,1,0,0,0,0,...,1,1,0,0,1,0,0,0,1,1.1901
24,912.83,1,1,1,1,0,1,0,0,0,...,0,0,0,0,0,1,1,0,1,1.2901
25,-512.17,1,0,0,1,0,1,0,0,1,...,0,1,0,1,0,1,1,1,1,1.4401
26,-1512.17,1,0,0,1,0,1,1,0,0,...,0,1,0,0,1,0,0,1,1,0.9901
27,-1112.17,1,1,0,1,0,1,0,0,1,...,0,1,0,0,1,0,1,1,1,1.4401
28,-1637.17,1,1,0,0,0,1,1,0,1,...,1,1,0,0,0,1,0,0,1,1.3401
29,462.83,1,1,0,1,0,0,0,0,0,...,1,0,0,0,0,1,1,1,1,1.0401
30,-87.17,1,0,0,1,1,1,0,0,1,...,1,0,1,0,0,1,0,0,1,1.3901
31,-1012.17,0,0,0,1,0,1,1,0,0,...,0,1,0,1,1,0,1,0,1,0.9901
32,62.83,0,1,1,1,0,1,0,0,0,...,1,0,1,0,1,1,0,1,1,1.3901
33,-837.17,0,1,0,1,1,1,0,0,0,...,0,1,1,1,0,1,0,1,1,1.6401
34,-387.17,1,0,1,0,1,1,0,0,1,...,1,0,1,1,0,0,0,0,1,1.5901

In [168]:
# sample all

OLSmodel(df[['Y',    '橄榄', '舞王',  '冰车',  '气球', '矿工',  '红眼', '权重和']],False)

                                 OLS Regression Results
=======================================================================================
Dep. Variable:                      Y   R-squared (uncentered):                   0.904
Model:                            OLS   Adj. R-squared (uncentered):              0.880
Method:                 Least Squares   F-statistic:                              37.62
Date:                Sun, 04 May 2025   Prob (F-statistic):                    1.34e-12
Time:                        07:15:11   Log-Likelihood:                         -241.22
No. Observations:                  35   AIC:                                      496.4
Df Residuals:                      28   BIC:                                      507.3
Df Model:                           7
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
橄榄           790.8025     99.639      7.937      0.000     586.701     994.904
舞王           325.7131     99.162      3.285      0.003     122.589     528.837
冰车           415.8345     97.934      4.246      0.000     215.225     616.444
气球          1151.9396    108.845     10.583      0.000     928.981    1374.898
矿工           500.9160    110.319      4.541      0.000     274.938     726.894
红眼           622.5817    111.578      5.580      0.000     394.024     851.140
权重和        -1460.7076    133.177    -10.968      0.000   -1733.508   -1187.907
==============================================================================
Omnibus:                        1.693   Durbin-Watson:                   1.324
Prob(Omnibus):                  0.429   Jarque-Bera (JB):                1.087
Skew:                           0.043   Prob(JB):                        0.581
Kurtosis:                       2.141   Cond. No.                         8.17
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.

               0
橄榄    790.802476
舞王    325.713051
冰车    415.834477
气球   1151.939574
矿工    500.915951
红眼    622.581711
权重和 -1460.707642