In [46]:
# Kevin

In [47]:
import pandas as pd
import statsmodels.api as sm
from matplotlib import pyplot as plt  

df = pd.read_excel('2.1阳光信息.xlsx')
df['权重和']=df['权重和']/10000
df = df.drop('flag',axis=1)
# df
df.columns

Index(['Y', '路障', '撑杆', '铁桶', '读报', '铁门', '橄榄', '舞王', '潜水', '冰车', '海豚', '小丑',
       '气球', '矿工', '跳跳', '蹦极', '扶梯', '投篮', '白眼', '红眼', '权重和'],
      dtype='object')

In [48]:
# handle
df['Y'][:] -= 91.63
df

C:\Users\Administrator\AppData\Local\Temp\ipykernel_11052\2789549370.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Y'][:] -= 91.63
C:\Users\Administrator\AppData\Local\Temp\ipykernel_11052\2789549370.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Y'][:] -= 91.63
C:\Users\Administrator\AppData\Local\Temp\ipykernel_11052\2789549370.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ -516.63  -166.63   633.37    33.37   483.37   758.37   833.37  -816.63
  1833.37  -641.63  -166.63  1283.37  -891.63  -241.63   733.37  1458.37
   308.37  -941.63  -741.63 -1191.63  -591.63  -516.63  -616.63  -466.63
  -666.63]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df['Y'][:] -= 91.63

,Y,路障,撑杆,铁桶,读报,铁门,橄榄,舞王,潜水,冰车,...,小丑,气球,矿工,跳跳,蹦极,扶梯,投篮,白眼,红眼,权重和
0,-516.63,1,0,0,1,1,1,0,0,0,...,1,1,0,1,0,0,0,1,1,1.4401
1,-166.63,1,0,0,1,1,0,0,0,0,...,1,0,0,1,1,0,1,1,1,1.1901
2,633.37,1,1,1,1,0,0,0,0,0,...,1,1,0,0,0,1,1,0,0,1.2901
3,33.37,1,1,1,0,1,0,0,0,1,...,0,0,0,0,1,1,1,0,1,1.5401
4,483.37,0,1,1,1,1,0,0,0,0,...,1,1,0,1,0,0,1,0,0,1.5401
5,758.37,1,1,1,0,1,0,0,0,0,...,0,1,0,0,1,1,1,0,0,1.4401
6,833.37,1,0,1,0,1,1,0,0,1,...,0,0,0,1,1,1,0,1,0,1.5401
7,-816.63,1,1,1,1,0,1,0,0,1,...,1,1,0,0,0,0,1,0,1,1.6901
8,1833.37,1,0,1,1,0,0,0,0,1,...,1,0,0,0,1,1,1,0,0,1.0901
9,-641.63,1,1,0,0,1,0,0,0,0,...,1,1,0,1,1,1,0,0,1,1.2901
10,-166.63,1,1,1,1,0,1,0,0,1,...,1,0,0,0,0,0,0,0,1,1.3401
11,1283.37,1,0,1,1,1,0,0,0,1,...,0,0,0,1,1,1,1,1,0,1.5901
12,-891.63,1,1,1,1,0,1,0,0,0,...,0,1,0,1,1,0,1,0,1,1.4901
13,-241.63,1,0,1,0,1,1,0,0,1,...,0,1,0,0,0,1,1,1,0,1.7901
14,733.37,1,1,0,1,1,0,0,0,1,...,1,0,0,1,0,1,0,1,0,1.4401
15,1458.37,1,0,1,1,1,0,0,0,1,...,1,0,0,1,0,0,0,1,0,1.4401
16,308.37,1,1,1,1,0,0,0,0,0,...,1,1,0,1,1,1,0,0,0,1.2401
17,-941.63,1,0,1,0,1,0,0,0,1,...,1,1,0,1,1,0,0,0,1,1.4901
18,-741.63,0,1,0,1,0,0,0,0,1,...,0,1,0,0,0,1,1,1,1,1.2401
19,-1191.63,1,0,1,0,1,0,0,0,0,...,0,1,0,0,1,1,1,1,1,1.4901
20,-591.63,1,1,0,1,1,1,0,0,1,...,0,1,0,0,0,0,1,0,1,1.6401
21,-516.63,1,1,1,1,0,1,0,0,1,...,1,0,0,0,0,1,1,0,1,1.5901
22,-616.63,1,1,0,1,0,1,0,0,1,...,0,1,0,0,0,1,1,1,0,1.4401
23,-466.63,1,1,0,0,1,1,0,0,0,...,0,0,0,1,0,1,1,1,1,1.4901
24,-666.63,1,0,1,1,0,0,0,0,1,...,0,1,0,1,0,1,0,0,1,1.2401

In [49]:
def OLSmodel(df,const=True):
    X = df.iloc[:,1:]
    y = -df['Y']
    X_sm = sm.add_constant(X) if const else X
    model_sm = sm.OLS(y, X_sm).fit()
    print(model_sm.summary())
    return pd.DataFrame(model_sm.params)

In [50]:
# OLSmodel(df[['Y', '撑杆', '铁桶',  '铁门', '橄榄',  '冰车',  '小丑','气球',  '跳跳', '蹦极', '扶梯', '投篮', '白眼', '红眼', '权重和']],True)
# OLSmodel(df[['Y', '撑杆', '铁桶',  '铁门', '橄榄',  '冰车',  '小丑','气球',  '蹦极',  '投篮', '白眼', '红眼', '权重和']],True)
OLSmodel(df[['Y',   '橄榄',   '气球',   '白眼', '红眼']],True)

                            OLS Regression Results
==============================================================================
Dep. Variable:                      Y   R-squared:                       0.876
Model:                            OLS   Adj. R-squared:                  0.851
Method:                 Least Squares   F-statistic:                     35.29
Date:                Sat, 10 May 2025   Prob (F-statistic):           8.47e-09
Time:                        06:37:29   Log-Likelihood:                -176.83
No. Observations:                  25   AIC:                             363.7
Df Residuals:                      20   BIC:                             369.8
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1368.5346    153.265     -8.929      0.000   -1688.240   -1048.829
橄榄           308.1184    135.426      2.275      0.034      25.625     590.612
气球           823.2991    135.266      6.087      0.000     541.139    1105.460
白眼           287.1101    136.748      2.100      0.049       1.859     572.362
红眼          1174.3023    135.559      8.663      0.000     891.532    1457.073
==============================================================================
Omnibus:                        1.082   Durbin-Watson:                   1.915
Prob(Omnibus):                  0.582   Jarque-Bera (JB):                0.539
Skew:                          -0.360   Prob(JB):                        0.764
Kurtosis:                       3.020   Cond. No.                         4.79
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

                 0
const -1368.534612
橄榄      308.118443
气球      823.299127
白眼      287.110106
红眼     1174.302342