In [31]:
# both

In [32]:
import pandas as pd
import statsmodels.api as sm
from matplotlib import pyplot as plt  

df = pd.read_excel('2.2阳光信息.xlsx')
df['权重和']=df['权重和']/10000
df = df.drop('flag',axis=1)
# df
df.columns

Index(['Y', '路障', '撑杆', '铁桶', '读报', '铁门', '橄榄', '舞王', '潜水', '冰车', '海豚', '小丑',
       '气球', '矿工', '跳跳', '蹦极', '扶梯', '投篮', '白眼', '红眼', '权重和'],
      dtype='object')

In [33]:
# handle
df['Y'][:14] -= 108.45 
df['Y'][14:26] -= 44.47 
df['Y'][26:] -= 91.63
df

C:\Users\Administrator\AppData\Local\Temp\ipykernel_26588\3707809142.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Y'][:14] -= 108.45
C:\Users\Administrator\AppData\Local\Temp\ipykernel_26588\3707809142.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Y'][:14] -= 108.45
C:\Users\Administrator\AppData\Local\Temp\ipykernel_26588\3707809142.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[   41.55  -158.45 -1133.45  -358.45 -1358.45  -883.45  -733.45  -533.45
  -208.45 -1083.45  -333.45 -1108.45  -558.45 -1033.45]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df['Y'][:14] -= 108.45
C:\Users\Administrator\AppData\Local\Temp\ipykernel_26588\3707809142.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Y'][14:26] -= 44.47
C:\Users\Administrator\AppData\Local\Temp\ipykernel_26588\3707809142.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Y'][26:] -= 91.63

,Y,路障,撑杆,铁桶,读报,铁门,橄榄,舞王,潜水,冰车,...,小丑,气球,矿工,跳跳,蹦极,扶梯,投篮,白眼,红眼,权重和
0,41.55,1,0,0,1,1,1,0,0,1,...,1,0,0,0,1,0,1,0,1,1.3401
1,-158.45,1,0,1,1,0,1,0,0,1,...,1,0,0,1,0,0,0,0,1,1.2401
2,-1133.45,1,1,0,1,0,1,0,0,0,...,0,1,0,0,1,1,0,1,1,1.1901
3,-358.45,1,1,1,1,1,1,0,0,0,...,1,0,0,1,0,0,0,1,1,1.7401
4,-1358.45,1,0,1,0,0,1,0,0,1,...,0,1,0,0,1,0,1,0,1,1.2901
5,-883.45,1,1,1,0,0,0,0,0,0,...,1,1,0,0,1,1,1,0,1,1.2901
6,-733.45,1,1,0,1,1,0,0,0,0,...,0,1,0,0,0,1,1,0,1,1.3401
7,-533.45,1,1,0,0,0,1,0,0,1,...,1,0,0,1,1,0,1,0,1,1.1901
8,-208.45,1,1,1,1,0,0,0,0,0,...,1,0,0,1,0,0,0,1,1,1.1901
9,-1083.45,1,0,0,1,0,0,0,0,1,...,1,1,0,1,0,1,1,0,1,1.1901
10,-333.45,1,0,0,0,1,0,0,0,1,...,0,0,0,1,0,1,1,1,1,1.2901
11,-1108.45,1,0,0,1,0,1,0,0,0,...,1,0,0,0,1,0,1,1,1,0.9401
12,-558.45,1,0,0,1,1,1,0,0,0,...,1,0,0,0,1,0,1,1,1,1.2901
13,-1033.45,1,0,0,1,0,1,0,0,1,...,0,1,0,1,0,1,1,0,1,1.2901
14,430.53,1,1,0,1,1,0,0,0,0,...,1,1,0,0,1,0,1,1,0,1.3901
15,1655.53,1,1,1,1,1,0,0,0,1,...,1,0,0,1,0,1,1,0,0,1.7401
16,655.53,1,0,1,0,1,1,0,0,0,...,1,1,0,0,1,1,1,0,0,1.5401
17,455.53,1,0,1,1,0,0,0,0,0,...,1,1,0,1,0,1,0,1,0,1.1901
18,1380.53,1,0,1,1,1,0,0,0,1,...,0,0,0,1,0,1,0,1,0,1.4401
19,705.53,1,0,1,1,0,1,0,0,0,...,1,0,0,1,0,0,1,1,0,1.2401
20,580.53,1,1,1,1,1,1,0,0,1,...,0,0,0,1,0,0,0,1,0,1.7401
21,1805.53,1,0,1,0,1,0,0,0,1,...,1,0,0,1,0,1,1,0,0,1.4401
22,105.53,1,1,0,0,1,0,0,0,1,...,0,1,0,1,1,1,0,1,0,1.4401
23,1255.53,1,1,0,1,1,1,0,0,0,...,1,0,0,0,0,1,1,1,0,1.4901
24,505.53,1,1,1,1,1,1,0,0,1,...,0,1,0,1,1,0,0,0,0,1.7901
25,505.53,1,0,1,1,1,0,0,0,0,...,1,1,0,1,1,1,1,0,0,1.5401
26,-516.63,1,0,0,1,1,1,0,0,0,...,1,1,0,1,0,0,0,1,1,1.4401
27,-166.63,1,0,0,1,1,0,0,0,0,...,1,0,0,1,1,0,1,1,1,1.1901
28,633.37,1,1,1,1,0,0,0,0,0,...,1,1,0,0,0,1,1,0,0,1.2901
29,33.37,1,1,1,0,1,0,0,0,1,...,0,0,0,0,1,1,1,0,1,1.5401
30,483.37,0,1,1,1,1,0,0,0,0,...,1,1,0,1,0,0,1,0,0,1.5401
31,758.37,1,1,1,0,1,0,0,0,0,...,0,1,0,0,1,1,1,0,0,1.4401
32,833.37,1,0,1,0,1,1,0,0,1,...,0,0,0,1,1,1,0,1,0,1.5401
33,-816.63,1,1,1,1,0,1,0,0,1,...,1,1,0,0,0,0,1,0,1,1.6901
34,1833.37,1,0,1,1,0,0,0,0,1,...,1,0,0,0,1,1,1,0,0,1.0901
35,-641.63,1,1,0,0,1,0,0,0,0,...,1,1,0,1,1,1,0,0,1,1.2901
36,-166.63,1,1,1,1,0,1,0,0,1,...,1,0,0,0,0,0,0,0,1,1.3401
37,1283.37,1,0,1,1,1,0,0,0,1,...,0,0,0,1,1,1,1,1,0,1.5901
38,-891.63,1,1,1,1,0,1,0,0,0,...,0,1,0,1,1,0,1,0,1,1.4901
39,-241.63,1,0,1,0,1,1,0,0,1,...,0,1,0,0,0,1,1,1,0,1.7901
40,733.37,1,1,0,1,1,0,0,0,1,...,1,0,0,1,0,1,0,1,0,1.4401
41,1458.37,1,0,1,1,1,0,0,0,1,...,1,0,0,1,0,0,0,1,0,1.4401
42,308.37,1,1,1,1,0,0,0,0,0,...,1,1,0,1,1,1,0,0,0,1.2401
43,-941.63,1,0,1,0,1,0,0,0,1,...,1,1,0,1,1,0,0,0,1,1.4901
44,-741.63,0,1,0,1,0,0,0,0,1,...,0,1,0,0,0,1,1,1,1,1.2401
45,-1191.63,1,0,1,0,1,0,0,0,0,...,0,1,0,0,1,1,1,1,1,1.4901
46,-591.63,1,1,0,1,1,1,0,0,1,...,0,1,0,0,0,0,1,0,1,1.6401
47,-516.63,1,1,1,1,0,1,0,0,1,...,1,0,0,0,0,1,1,0,1,1.5901
48,-616.63,1,1,0,1,0,1,0,0,1,...,0,1,0,0,0,1,1,1,0,1.4401
49,-466.63,1,1,0,0,1,1,0,0,0,...,0,0,0,1,0,1,1,1,1,1.4901
50,-666.63,1,0,1,1,0,0,0,0,1,...,0,1,0,1,0,1,0,0,1,1.2401

In [34]:
def OLSmodel(df,const=True):
    X = df.iloc[:,1:]
    y = -df['Y']
    X_sm = sm.add_constant(X) if const else X
    model_sm = sm.OLS(y, X_sm).fit()
    print(model_sm.summary())
    return pd.DataFrame(model_sm.params)

In [35]:
# OLSmodel(df[['Y', '撑杆', '铁桶',  '铁门', '橄榄',  '冰车',  '小丑','气球',  '跳跳', '蹦极', '扶梯', '投篮', '白眼', '红眼', '权重和']],True)
# OLSmodel(df[['Y', '撑杆', '铁桶',  '铁门', '橄榄',  '冰车',  '小丑','气球',  '蹦极',  '投篮', '白眼', '红眼', '权重和']],True)
OLSmodel(df[['Y',  '铁门', '橄榄', '气球', '白眼', '红眼']],True)

# OLSmodel(df[['Y',   '橄榄',   '气球',   '白眼', '红眼']],True)

                            OLS Regression Results
==============================================================================
Dep. Variable:                      Y   R-squared:                       0.906
Model:                            OLS   Adj. R-squared:                  0.895
Method:                 Least Squares   F-statistic:                     86.64
Date:                Sat, 10 May 2025   Prob (F-statistic):           6.09e-22
Time:                        06:47:36   Log-Likelihood:                -356.17
No. Observations:                  51   AIC:                             724.3
Df Residuals:                      45   BIC:                             735.9
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1350.0558    116.722    -11.566      0.000   -1585.147   -1114.965
铁门          -177.6629     85.292     -2.083      0.043    -349.451      -5.875
橄榄           265.3375     81.855      3.242      0.002     100.473     430.202
气球           813.9012     82.741      9.837      0.000     647.252     980.550
白眼           359.5083     84.116      4.274      0.000     190.090     528.926
红眼          1336.7425     83.693     15.972      0.000    1168.177    1505.308
==============================================================================
Omnibus:                        0.439   Durbin-Watson:                   2.067
Prob(Omnibus):                  0.803   Jarque-Bera (JB):                0.373
Skew:                          -0.198   Prob(JB):                        0.830
Kurtosis:                       2.863   Cond. No.                         6.00
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

                 0
const -1350.055788
铁门     -177.662911
橄榄      265.337542
气球      813.901169
白眼      359.508326
红眼     1336.742504